export default {
  getUserInfo: '/api/auth/userinfo',
  login: '/api/auth/login',
  logout: '/api/auth/logout',
  userList: '/api/user/list',
  userCreate: '/api/user',
  userUpdate: '/api/user',
  userDelete: '/api/user/{id}',
  roleList: '/api/role/list',
  roleCreate: '/api/role',
  roleUpdate: '/api/role',
  roleDelete: '/api/role/{id}',
  permissionList: '/api/permission/list',
  permissionMenu: '/api/permission/menu',
  permissionCreate: '/api/permission',
  permissionUpdate: '/api/permission',
  permissionDelete: '/api/permission/{id}',
  statistics: '/api/statistics',
  dashboard: '/api/dashboard',
};
